/**
 * generated by Xtext 2.12.0
 */
package org.example.domainmodel.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class DomainmodelIdeModule /* implements AbstractDomainmodelIdeModule  */{
}
