/**
 * generated by Xtext 2.12.0
 */
package org.example.domainmodel.ide;

import com.google.inject.Injector;
import org.example.domainmodel.DomainmodelStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class DomainmodelIdeSetup extends DomainmodelStandaloneSetup {
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from DomainmodelIdeModule to Module");
  }
}
