/**
 * generated by Xtext 2.12.0
 */
package org.example.domainmodel.ui;

import com.google.inject.Module;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.example.domainmodel.ui.AbstractDomainmodelUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class DomainmodelUiModule extends AbstractDomainmodelUiModule implements Module {
  public DomainmodelUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
