/*
 * generated by Xtext 2.12.0
 */
package org.example.domainmodel.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor
import com.google.inject.Module

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class DomainmodelUiModule extends AbstractDomainmodelUiModule implements Module {
}
